version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./bonjack-tools-website-v2/
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
    ports:
      - 3000:80
    environment:
      - REACT_APP_WEBSOCKET_ENDPOINT="wss://${DOMAIN}/ws"
      - REACT_APP_HTTP_ENDPOINT="https://${DOMAIN}/api"
  backend:
    container_name: backend
    build:
      context: ./bonjack-tools-backend/
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./data:/data
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - CHANNEL_ID=212369829582077953
      - TEXT_CHANNEL_ID=212369747973636097
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_URL=file:/data/ldn-prod.db
