version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./bonjack-tools-website-v2/
      dockerfile: Dockerfile.dev
    volumes:
      - ./bonjack-tools-website-v2:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_WEBSOCKET_ENDPOINT="ws://localhost:3001/"
      - REACT_APP_HTTP_ENDPOINT="http://localhost:3001/api"
      - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
      - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
      - REACT_APP_AUTH0_AUDIENCE=${AUDIENCE}
  backend:
    container_name: backend
    build:
      context: ./bonjack-tools-backend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./bonjack-tools-backend/:/usr/app
      - /usr/app/node_modules
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - CHANNEL_ID=212369829582077953
      - TEXT_CHANNEL_ID=212369747973636097
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_URL=file:/usr/app/dev.db?connection_limit=1
      - RIOT_API_KEY=${RIOT_API_KEY}
      - ISSUER_BASE_URL=${ISSUER_BASE_URL}
      - AUDIENCE=${AUDIENCE}

