FROM node:alpine
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY ./ ./
RUN npm install -g typescript
RUN npm install -g ts-node
RUN npm i
RUN npx prisma generate
USER node
CMD ["npm", "run", "dev"]